-- ==========================================
-- SCRIPT DE CONFIGURACIÓN DE SUPABASE
-- Ejecutar en el SQL Editor de Supabase
-- ==========================================

-- 1. Creación de la Tabla de Leads de Contacto
create table if not exists public.contacts_leads (
    id uuid default gen_random_uuid() primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    name text not null,
    email text not null,
    message text not null,
    demo_id text,
    status text default 'nuevo' not null
);

-- Habilitar RLS en contacts_leads
alter table public.contacts_leads enable row level security;

-- Política RLS: Permitir que cualquiera inserte un formulario (Público / Anon)
create policy "Permitir inserción pública anónima de leads"
on public.contacts_leads
for insert
with check (true);

-- Política RLS: Permitir lectura/escritura total solo a usuarios autenticados (Admin)
create policy "Permitir acceso total a administradores autenticados"
on public.contacts_leads
for all
to authenticated
using (true)
with check (true);


-- 2. Creación de la Tabla de Eventos de Interacción de las Demos
create table if not exists public.demo_events (
    id uuid default gen_random_uuid() primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    demo_name text not null,
    event_type text not null, -- Ej: 'click', 'play', 'completed', 'open'
    user_agent text,
    metadata jsonb default '{}'::jsonb not null
);

-- Habilitar RLS en demo_events
alter table public.demo_events enable row level security;

-- Política RLS: Permitir inserción pública anónima de eventos
create policy "Permitir inserción pública anónima de eventos"
on public.demo_events
for insert
with check (true);

-- Política RLS: Permitir lectura/escritura total solo a usuarios autenticados (Admin)
create policy "Permitir acceso total de eventos a administradores autenticados"
on public.demo_events
for all
to authenticated
using (true)
with check (true);


-- 3. Creación de la Tabla de Pedidos (Demo Kanban)
create table if not exists public.orders (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    cliente text not null,
    email text not null,
    productos jsonb default '[]'::jsonb not null,
    estado text default 'pendiente' not null,
    session_id text
);

-- Habilitar RLS en orders
alter table public.orders enable row level security;

-- Política RLS: Permitir lectura pública de pedidos
create policy "Permitir lectura pública de pedidos"
on public.orders
for select
using (true);

-- Política RLS: Permitir inserción pública de pedidos
create policy "Permitir inserción pública de pedidos"
on public.orders
for insert
with check (true);

-- Política RLS: Permitir actualización pública de pedidos (para mover tarjetas en el Kanban)
create policy "Permitir actualización pública de pedidos"
on public.orders
for update
using (true)
with check (true);


-- 4. Creación de la Tabla de Reservas (Demo Maps & Calendar)
create table if not exists public.bookings (
    id uuid default gen_random_uuid() primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    cliente text not null,
    email text not null,
    fecha_hora timestamp with time zone not null,
    direccion text not null,
    latitud double precision,
    longitud double precision,
    estado text default 'confirmado' not null,
    chofer text,
    auto text,
    session_id text
);

-- Habilitar RLS en bookings
alter table public.bookings enable row level security;

-- Política RLS: Permitir lectura pública de reservas
create policy "Permitir lectura pública de reservas"
on public.bookings
for select
using (true);

-- Política RLS: Permitir inserción pública de reservas
create policy "Permitir inserción pública de reservas"
on public.bookings
for insert
with check (true);

-- Política RLS: Permitir actualización pública de reservas (para asignar chofer/auto)
create policy "Permitir actualización pública de reservas"
on public.bookings
for update
using (true)
with check (true);


-- 5. Índices para Optimización de Consultas
create index if not exists idx_contacts_leads_created_at on public.contacts_leads(created_at desc);
create index if not exists idx_demo_events_demo_name on public.demo_events(demo_name);
create index if not exists idx_demo_events_event_type on public.demo_events(event_type);
create index if not exists idx_demo_events_created_at on public.demo_events(created_at desc);
create index if not exists idx_orders_created_at on public.orders(created_at desc);
create index if not exists idx_orders_session_id on public.orders(session_id);
create index if not exists idx_bookings_created_at on public.bookings(created_at desc);
create index if not exists idx_bookings_session_id on public.bookings(session_id);

